name: glpi

services:
  glpi:
    image: "glpi/glpi:latest"
    restart: "unless-stopped"
    volumes:
      # Using a named volume avoids permission issues on host (automatically managed by Docker)
      - glpi_data:/var/glpi
      # For GLPI 10.x, uncomment the following line to create a volume for plugins fetched from the marketplace.
      # - "./storage/glpi_marketplace:/var/www/glpi/marketplace/:rw"
    env_file: .env
    depends_on:
      - db
    ports:
      - "80:80"

  db:
    image: "mysql"
    restart: "unless-stopped"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${GLPI_DB_NAME}
      MYSQL_USER: ${GLPI_DB_USER}
      MYSQL_PASSWORD: ${GLPI_DB_PASSWORD}
  
  postgres:
    image: postgres:16
    container_name: tickets_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${TICKETS_DB_USER}
      POSTGRES_PASSWORD: ${TICKETS_DB_PASSWORD}
      POSTGRES_DB: ${TICKETS_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TICKETS_DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: ./api_server/server/server
      dockerfile: Dockerfile
    container_name: api_server
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=${TICKETS_DB_NAME};Username=${TICKETS_DB_USER};Password=${TICKETS_DB_PASSWORD}"
      Glpi__BaseUrl: "http://glpi"
      Glpi__ClientId: ${GLPI_CLIENT_ID}
      Glpi__ClientSecret: ${GLPI_CLIENT_SECRET}
      Glpi__Username: ${GLPI_ADMIN_USER}
      Glpi__Password: ${GLPI_ADMIN_PASSWORD}
      ASPNETCORE_URLS: "http://+:8080"
    ports:
      - "5237:8080"

  frontend:
    build:
      context: ./fronted
      dockerfile: Dockerfile
    container_name: react_app
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"
volumes:
  glpi_data:
  db_data:
  pgdata:
